os: linux
dist: bionic
language: generic
services:
- docker
before_script:
- bash hack/prepare.sh
script:
- bash hack/build.sh
deploy:
- provider: script
  script: bash hack/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - DOCKER_USER=aintdiscole
  - secure: "vCHVR/XCfZqw2wtiPQwu+dHne1Z7cW/0r8fxIQw93fNFPZrz9xfdTNqGIGUF6dXG1lwhXPQiBWn8pjyLCneIga3WLQR1tSi8WHrV8GQnwwYkDTfbqf9XpjWJxn5MjCMNhIZWEFZwk6mEcb55gZdUPj5nH1oKYh70491dBBWINO1PBT3R2S6HtobDzdUHD2HCBPqnA22ihrmOJLaGEGTT0+j57m0/EMzBDMNGpi4pUwbcDEx6zYxWkAUeBjR+4WQyofwtW5fLk92qZNQKGqUWN66jUUClbSNdpe5/2l7qAv6OD3rPjFO2qdACUKRDnAv+9hKK+0ZfH11aDh0JghK3FuvqHBe8UkC+52/S9tBhfVZhr/qAL2/vZQE3re5entZ/v9dgkl9mdEr/OVw7alj6GA9RL51RT6vsnKhnFLdwSUynJVqC1BcShxCrwYatX16K0LVGT47r8vn88zipfb7nkKKUZtfhuVf/qhQJM03q+2xI2Ui/GbHdPWjY35Q6ymLdnLeG/J0ZIyKvn274iSdeP7Sd9hQ+y/QS3e0tMu87AWXev0uED0U/kEEgfTiOPCgaeFDzQKM2r50bPOka1XIoHnX6//uIiHCFIeR7dq6EGs5xl/5JNxeNmq0vZns4K/yXSMTKB6r9QO/KKqrxJ9AqJBqP53K9Zj7zM0m+RyuAJ78="
